services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: avalanche_dev
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    build: .
    ports:
      - 5000:5000
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/avalanche_dev?schema=public&connection_limit=40
      - PORT=5000
      - AVA_BASE_URL=https://avalanche-mainnet.infura.io/v3/YOURAPIKEY